config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
  get 'flats/:id', to: 'flats#show', as: :flat
  # get 'flats/148', to: 'flats#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  before_action :fetch_flats

  def index
    # url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    # @flats = JSON.parse(open(url).read)
    # raise
  end

  def show
    # url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    # @flats = JSON.parse(open(url).read)
    @flat = @flats.find { |flat| flat['id'] == params[:id].to_i }
  end

  private

  def fetch_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>

<!-- convention to add a link:
 --><%#= link_to 'name of the link', '#' %>
<ul>
  <% @flats.each do |flat| %>
    <li><%= link_to flat["name"], flat_path(flat['id']) %>, <%= "#{flat["price"]} #{flat["priceCurrency"]}" %></li>
  <% end %>

</ul>

app/views/flats/show.html.erb
<h3><%= @flat["name"] %></h3>

<%= image_tag @flat["imageUrl"], alt: "photo of flat", width: 300 %></p>
<p>Price per night: <%= @flat["price"] %> <%= @flat["priceCurrency"] %></p>

<br>

<%= link_to "Home", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<!--     <#%= params.each do |key, value| %>
      <li>params[:<#%= key %>] = <#%= value %></li>
    <#% end %> -->
    <%= params %>
    <%= yield %>
  </body>
</html>